### ISSUE TITLE
Rider 2018.2.2 - wheel gets broken when closing a file.

### ISSUE THREAD

**Issue by IcyStares** [skydi17/navigation-wheel-plugin#1]
Steps:
Open rider and scripts
Open plugin(alt + c + x)
Close one of the tabs
Observe the issue: circle behind the buttons is not drawn and the wheel seem to be frozen.

**Comment by skydi17** [comment]
Thanks for finding bugs.
Fixed in 43 commit. WIll be delivered with 2.0 version.
